### ISSUE TITLE
Make powerpoint slides

### ISSUE THREAD

**Issue by ren-nay** [ren-nay/TechDawgsTurtleWorkshop#2]

**Comment by ren-nay** [comment]
- [ ] Verify powerpoints can be shared on github (or just upload link)
- [ ] powerpoint slides include basic outline of event (intro, lecture, code/tutorial, picture printing, ending...)

**Comment by DTVMAN01** [comment]
https://docs.google.com/presentation/d/18G5Q1EpTXbi25EPRhJYoS4ruyVKGiPm96DNJHrdhd38/edit?usp=sharing

**Comment by DTVMAN01** [comment]
https://docs.google.com/presentation/d/18G5Q1EpTXbi25EPRhJYoS4ruyVKGiPm96DNJHrdhd38/edit?usp=sharing
